[package]
name = "oem_cp"
version = "0.1.1"
authors = ["Tatsunori Uchino <tats.u@live.jp>"]
edition = "2018"
categories = ["encoding"]
keywords = ["encoding", "charset"]
license = "MIT"
description ="Rust library that handles OEM code pages (e.g. CP{437,737,850}) for single byte character sets"
readme = "README.md"
repository = "https://github.com/tats-u/rust-oem-cp/"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.8.1"
lazy_static = "1.4.0"